name=input("What is your name? ")
age=input("What is your age? ")
favorite_hobby=input("What is your favorite hobby? ")
favorite_food=input("What is your favorite food? ")
favorite_color=input("What is your favorite color? ")
print("PERONSAL PROFILE")
print(f"Name: {name}")
print(f"Age: {age}")
print(f"Favorite Hobby: {favorite_hobby}")
print(f"Favorite Food: {favorite_food}")
print(f"Favorite Color: {favorite_color}")
print(f"in 10 years you will be: {int(age) + 10}")
print("thank you for using my program!")