Name = input("What is your name? ")
Height = float(input("What is your height in inches? "))
Weight = float(input("What is your weight in pounds? "))
Goal_Weight = float(input("What is your goal weight in pounds? "))
print("Name:", Name)
print("Height:", Height, "inches")
print("Weight:", Weight, "pounds")
print("Goal Weight:", Goal_Weight, "pounds")
print("Weight to lose:", Weight - Goal_Weight, "pounds")
print("BMI:", round((Weight / (Height ** 2)) * 703, 1))
print("weeks to lose weight:", round((Weight - Goal_Weight) / 1.5, 2), "weeks")